ci: run for each new version

diff --git a/.github/workflows/detect-new-emoji-releases.yaml b/.github/workflows/detect-new-emoji-releases.yaml
--- a/.github/workflows/detect-new-emoji-releases.yaml
+++ b/.github/workflows/detect-new-emoji-releases.yaml
@@ -42,11 +42,22 @@ jobs:
           mojis_api_base_url: ${{ github.event.inputs.api-base-url }}
 
       - name: try to generate data
-        # if: steps.detect-new-releases.outputs.has_new_releases == 'true'
+        if: steps.detect-new-releases.outputs.has_new_releases == 'true'
+        env:
+          NEW_RELEASES: ${{ steps.detect-new-releases.outputs.unsupported_versions }}
         run: |
           echo "There is a new release!"
-          echo "${{ steps.detect-new-releases.outputs.has_new_releases }}"
-          echo "${{ steps.detect-new-releases.outputs.unsupported_versions }}"
+
+          # for each of the new releases, try to run mojis cli.
+          for release in $NEW_RELEASES; do
+            echo "trying to run mojis cli for release $release"
+            # try to run mojis cli
+            # if ! npx mojis --version $release; then
+            #   echo "Failed to run mojis cli for release $release"
+            #   echo "Please check the release version and try again."
+            #   exit 1
+            # fi
+          done
 
       # - name: create pull request
       #   id: create-pr
